# This file may be used to create an environment using conda:
#
# ## Miniconda or Anaconda
#
# Linux
#     $ conda env create -f environment.yml
# MacOS
#     $ conda env create -f environment.yml --subdir=osx-64
# If you are using the zsh shell, run:
#     $ conda init zsh
# Or, if you are using a different shell, run:
#     $ conda init
# After init, if you do not want conda to change your global shell when
# you open a new terminal, run:
#     $ conda config --set auto_activate_base false
# Finally, activate the environment with:
#     $ conda activate tbp.ultrasound_perception
#
name: tbp.ultrasound_perception
channels:
  - aihabitat
  - pytorch
  - pyg
  - defaults
  - conda-forge
  - thousandbrainsproject

dependencies:
  - thousandbrainsproject::tbp.monty==0.6.0
  - pip
  - pip:
    - -e .[dev]
